### ISSUE TITLE
글쓰기에서 모집 기한을 눌렀다가 상시 모집을 누르고 글을 저장하면 모집 기한이 생성됩니다.

### ISSUE THREAD

**Issue by yoonsoo7429** [CREW-service/FRONT#10]
# 문제 
 글쓰기에서 모집 기한을 눌렀다가 상시 모집을 누르고 글을 저장하면 모집 기한이 생성됩니다.

## 중요도 
- **매우 중요**

## 상세 
- 글쓰기에서 모집 기한을 눌렀다가 상시 모집을 누르고 글을 저장하면 모집 기한이 생성됩니다.

## 문제 재현 빈도 
- 항상

## 문제 위치
- 글쓰기

### 영향 받는 사용자 
- 로그인한 사용자

### 영향 받는 페이지 
- 글쓰기, 전체 map 글 목록

**Comment by FioreFlower** [comment]
해당 이슈를 해결하기 위해 코드를 수정했습니다. 
테스트 후 결과에 따라 이슈 종결하겠습니다.

**Comment by FioreFlower** [comment]
수정 된 코드에서 상시 모집 체크 박스가 눌리지 않는 문제 발생

**Comment by FioreFlower** [comment]
문제 해결했습니다. 

테스트 후 문제 없으면 이슈 종결해 주세요.

**Comment by FioreFlower** [comment]
수정 기능에서 문제가 발생하여 코드 수정했습니다. 
- 재현 여부 확인 바랍니다.

**Comment by FioreFlower** [comment]
@YOONSOO7429 
수정 API Payload 확인시 마감일 null로 전송했으나 반영되지 않아 BE에서 확인 부탁드립니다.
