### ISSUE TITLE
상세 글에서 삭제를 눌렀을 때 다시 홈 화면으로 돌아오지 않아요

### ISSUE THREAD

**Issue by yoonsoo7429** [CREW-service/FRONT#11]
# 문제 
 상세 글에서 삭제를 눌렀을 때 다시 홈 화면으로 돌아오지 않아요

## 중요도 
- **매우 중요**

## 상세 
- 상세 글에서 삭제를 눌렀을 때 다시 홈 화면으로 돌아오지 않아요

## 문제 재현 빈도 
- 항상

## 문제 위치
- 글 삭제

### 영향 받는 사용자 
- 로그인한 사용자

### 영향 받는 페이지 
- 글쓰기, 전체 map 글 목록

**Comment by FioreFlower** [comment]
나가기 기능도 동일하게 발생하는지 확인 후 처리 예정

**Comment by coderia8984** [comment]
해결했습니다
