### ISSUE TITLE
로그아웃 설정 메뉴 창닫힘

### ISSUE THREAD

**Issue by coderia8984** [CREW-service/FRONT#12]
# 문제 
로그아웃 설정 메뉴창이 페이지 이동해도 그대로 떠 있음 

## 중요도 
- **낮음**

## 상세 
- 로그아웃 설정 메뉴창 빈곳 클릭하면 닫히는거 필요합니다.
- 메뉴 누르고 페이지 이동하면 그대로 떠있어요

## 문제 재현 빈도 
- 항상

## 문제 위치
- 메인 홈

### 영향 받는 사용자 
- 로그인한 사용자
- 둘러보기 사용자

### 영향 받는 페이지 
- 글쓰기, 전체 map 글 목록

**Comment by FioreFlower** [comment]
해결책을 같이 고민해 보도록해요... ㅠㅠ

**Comment by FioreFlower** [comment]
디자인 전면 수정 예정으로 이 이슈도 잠정 종료합니다.
