### ISSUE TITLE
참여 인원 모달 외부 클릭시 화면 닫힘 안됩니다.

### ISSUE THREAD

**Issue by coderia8984** [CREW-service/FRONT#14]
# 문제 
참여 인원 모달 외부 클릭시 화면 닫힘 안됩니다.

## 중요도 
- **보통**

## 상세 
- 디테일 페이지 참여 인원 모달창 외부 클릭해도 그대로 유지됩니다.

## 문제 재현 빈도 
- 항상

## 문제 위치
- 디테일 페이지 

### 영향 받는 사용자 
- 로그인한 사용자

### 영향 받는 페이지 
- 디테일 페이지

**Comment by FioreFlower** [comment]
디자인 전면 수정 예정으로 이슈를 잠정 종료합니다.
